

[build]
  command = "npm install && npm run build"
  publish = "." # Publish from the root directory

[functions]
  directory = "functions" # Optional: If you're using Netlify Functions

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
